name: ecommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar_v2: ^4.2.8
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.8
  provider: ^6.1.1
  firebase_storage: ^11.5.6
  flutter_svg: ^2.0.10+1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppICon"
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

